/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 scene.gltf 
Author: M.Reslan (https://sketchfab.com/mreslan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mechanical-keyboard-aesthetic-44bb12d306864e2cb4256a61d4168942
Title: Mechanical Keyboard - Aesthetic
*/

import { useRef, useState, useEffect } from "react";
import { Canvas, useFrame } from "@react-three/fiber";
import {
  useGLTF,
  ContactShadows,
  Environment,
  OrbitControls,
} from "@react-three/drei";
export function Model(props) {
  const { nodes, materials } = useGLTF("/3d-file/keyboard-basic/scene.gltf");
  const ref = useRef();
  return (
    <group {...props} dispose={null} ref={ref}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          receiveShadow
          castShadow
          geometry={nodes.Object_2.geometry}
          material={materials.Big_Buttons}
          material-color={props.colorBigButton || "gray"}
        />
        <mesh
          receiveShadow
          castShadow
          geometry={nodes.Object_3.geometry}
          material={materials.Chassis}
          material-color={props.colorChassis || "gray"}
        />
        <mesh
          receiveShadow
          castShadow
          geometry={nodes.Object_4.geometry}
          material={materials.Small_Buttons}
          material-color={props.colorSmallButton || "gray"}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/keyboard-basic/scene.gltf");
